# Generated by Django 4.1.7 on 2023-03-04 15:14

import uuid

import django.db.models.deletion
import transcribee_backend.base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_document_yjs_content_documentupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=transcribee_backend.base.models.generate_worker_token,
                        max_length=128,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_seen", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("DIARIZE", "Diarize"),
                            ("TRANSCRIBE", "Transcribe"),
                            ("ALIGN", "Align"),
                        ],
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField()),
                (
                    "task_parameters",
                    models.JSONField(
                        help_text="Task parameters like language, number of speakers, ..."
                    ),
                ),
                ("last_keepalive", models.DateTimeField(auto_now=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.worker",
                    ),
                ),
                ("dependency", models.ManyToManyField(to="base.task")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.document"
                    ),
                ),
            ],
        ),
    ]
