# Generated by Django 4.1.7 on 2023-03-12 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_task_progress_alter_task_task_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
