# Generated by Django 4.1.7 on 2023-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_task_assigned_at_task_completed_task_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_data",
            field=models.JSONField(default=dict),
        ),
    ]
