# Generated by Django 4.1.7 on 2023-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_task_completion_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dependency",
            field=models.ManyToManyField(blank=True, to="base.task"),
        ),
    ]
