# Generated by Django 4.1.7 on 2023-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_task_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(null=True),
        ),
    ]
