# Generated by Django 4.1.7 on 2023-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_task_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
