# Generated by Django 4.1.7 on 2023-03-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_task_assigned_at"),
        ("base", "0008_alter_worker_last_seen"),
    ]

    operations = []
