# Generated by Django 4.1.7 on 2023-03-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_merge_20230321_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.worker",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="task",
            name="progress",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Task parameters like language, number of speakers, ...",
            ),
        ),
    ]
