"""add usertoken model

Revision ID: 0ba2a5aa5df9
Revises: ace5dceb9f0f
Create Date: 2023-03-03 18:42:40.036639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0ba2a5aa5df9'
down_revision = 'ace5dceb9f0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertoken',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('token_salt', sa.LargeBinary(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usertoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usertoken_id'), ['id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('password_salt', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('password_salt')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('usertoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usertoken_id'))

    op.drop_table('usertoken')
    # ### end Alembic commands ###
