FROM ubuntu

RUN apt-get update && apt-get install -y xz-utils curl systemd sudo git
RUN echo "%ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ubuntu
WORKDIR /home/ubuntu

# install nix
RUN curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install > install-nix.sh
RUN sh install-nix.sh --no-daemon --yes
RUN mkdir -p ~/.config/nix/
RUN echo "experimental-features = nix-command flakes" > .config/nix/nix.conf
ENV PATH=$PATH:/home/ubuntu/.nix-profile/bin

WORKDIR /workspace

# prefill nix store
COPY --chown=ubuntu flake.nix /workspace/flake.nix
RUN nix develop

CMD ["nix", "develop"]
