name: transcribee

services:
  backend:
    build:
      dockerfile: ./packaging/docker/Dockerfile
      context: ..
    environment:
      TRANSCRIBEE_BACKEND_DATABASE_URL: postgresql://transcribee:transcribee@db:5432/transcribee
      REDIS_URL: redis://redis
      TESTUSER_PASSWORD: test
      WORKER_TOKEN_PATH: /var/transcribee/worker_token/token.txt
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - transcribee-storage:/var/transcribee/storage
      - worker-token:/var/transcribee/worker_token
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build:
      dockerfile: ./packaging/docker/worker.Dockerfile
      context: ..
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - worker-token:/var/transcribee/worker_token
    command: --coordinator http://backend:8000 --token-file /var/transcribee/worker_token/token.txt

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: transcribee
      POSTGRES_USER: transcribee
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d transcribee -U transcribee"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:8
    restart: always

volumes:
  postgres-data:
  transcribee-storage:
  worker-token:
