name: transcribee

services:
  backend:
    build:
      dockerfile: ./packaging/docker/Dockerfile
      context: ..
    environment:
      TRANSCRIBEE_BACKEND_DATABASE_URL: postgresql://transcribee:transcribee@db:5432/transcribee
      REDIS_HOST: redis
      TESTUSER_PASSWORD: test
      DEFAULT_WORKER_TOKEN: dev_worker
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - postgres-data:/var/lib/postgresql
  worker:
    build:
      dockerfile: ./packaging/docker/worker.Dockerfile
      context: ..
    command: ["--coordinator", "http://backend:8000", "--token", "dev_worker" ]
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: transcribee
      POSTGRES_USER: transcribee
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d transcribee -U transcribee"]
      interval: 1s
      timeout: 5s
      retries: 10
  redis:
    image: redis:8
    restart: always

volumes:
  postgres-data:
