"""add Task.completion_data & Document.duration fields

Revision ID: 14b5324ec3e2
Revises: 1ec1e251173a
Create Date: 2023-05-10 10:17:31.240419

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "14b5324ec3e2"
down_revision = "1ec1e251173a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(sa.Column("duration", sa.Float(), nullable=True))

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completion_data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("completion_data")

    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_column("duration")

    # ### end Alembic commands ###
