"""Add Worker.deactivated_at flag

Revision ID: 417eece003cb
Revises: 937846561faf
Create Date: 2023-11-18 17:14:05.221788

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "417eece003cb"
down_revision = "937846561faf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("worker", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("worker", schema=None) as batch_op:
        batch_op.drop_column("deactivated_at")

    # ### end Alembic commands ###
