"""add name field to DocumentShareToken

Revision ID: 59c9184ab48b
Revises: 72c5eb8a46de
Create Date: 2023-07-13 19:04:49.545902

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "59c9184ab48b"
down_revision = "72c5eb8a46de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documentsharetoken", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="Unnamed Share Token",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documentsharetoken", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
