"""add DocumentShareToken

Revision ID: 72c5eb8a46de
Revises: 6392770332cd
Create Date: 2023-06-26 17:27:11.760730

"""
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "72c5eb8a46de"
down_revision = "6392770332cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentsharetoken",
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("token_salt", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documentsharetoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documentsharetoken_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documentsharetoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documentsharetoken_id"))

    op.drop_table("documentsharetoken")
    # ### end Alembic commands ###
