"""fix accidentially nullable fields

Revision ID: c88376bf4844
Revises: 417eece003cb
Create Date: 2025-01-14 16:23:54.386629

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c88376bf4844"
down_revision = "417eece003cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column("document_id", existing_type=sa.UUID(), nullable=False)

    with op.batch_alter_table("taskdependency", schema=None) as batch_op:
        batch_op.alter_column(
            "dependent_task_id", existing_type=sa.UUID(), nullable=False
        )
        batch_op.alter_column(
            "dependant_on_id", existing_type=sa.UUID(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskdependency", schema=None) as batch_op:
        batch_op.alter_column("dependant_on_id", existing_type=sa.UUID(), nullable=True)
        batch_op.alter_column(
            "dependent_task_id", existing_type=sa.UUID(), nullable=True
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column("document_id", existing_type=sa.UUID(), nullable=True)

    # ### end Alembic commands ###
