"""remove align task

Revision ID: c9d4c04a9125
Revises: c88376bf4844
Create Date: 2026-07-22 16:44:34.238395

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9d4c04a9125"
down_revision = "c88376bf4844"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        tasktype = sa.Enum(
            "IDENTIFY_SPEAKERS",
            "TRANSCRIBE",
            "REENCODE",
            "EXPORT",
            name="tasktype",
        )
        tasktype.create(batch_op.get_bind())
        batch_op.alter_column(
            "task_type",
            existing_type=sa.VARCHAR(),
            type_=tasktype,
            postgresql_using="task_type::tasktype",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "task_type",
            existing_type=sa.Enum(
                "IDENTIFY_SPEAKERS",
                "ALIGN",
                "TRANSCRIBE",
                "REENCODE",
                "EXPORT",
                name="tasktype",
            ),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
