"""cascade document & task deletion

Revision ID: fc7c9d045329
Revises: 14b5324ec3e2
Create Date: 2023-05-17 14:15:02.494618

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc7c9d045329"
down_revision = "14b5324ec3e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "document_id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.drop_constraint("fk_task_document_id_document", type_="foreignkey")
        batch_op.create_foreign_key(
            None,  # type: ignore
            "document",
            ["document_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("taskdependency", schema=None) as batch_op:
        batch_op.alter_column(
            "dependent_task_id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.alter_column(
            "dependant_on_id", existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.drop_constraint(
            "fk_taskdependency_dependent_task_id_task", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_taskdependency_dependant_on_id_task", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None,  # type: ignore
            "task",
            ["dependent_task_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            None,  # type: ignore
            "task",
            ["dependant_on_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskdependency", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore
        batch_op.create_foreign_key(
            "fk_taskdependency_dependant_on_id_task",
            "task",
            ["dependant_on_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_taskdependency_dependent_task_id_task",
            "task",
            ["dependent_task_id"],
            ["id"],
        )
        batch_op.alter_column(
            "dependant_on_id", existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "dependent_task_id", existing_type=sa.CHAR(length=32), nullable=False
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore
        batch_op.create_foreign_key(
            "fk_task_document_id_document", "document", ["document_id"], ["id"]
        )
        batch_op.alter_column(
            "document_id", existing_type=sa.CHAR(length=32), nullable=False
        )

    # ### end Alembic commands ###
