name: Docker images

on:
  pull_request:
  merge_group:

permissions:
  contents: read
  packages: write

jobs:
  backend:
    uses: ./.github/workflows/.build-push-docker-image.yml
    with:
      image_name: ${{ github.repository }}
      dockerfile: ./packaging/docker/Dockerfile
      cache_mode: max

  worker:
    uses: ./.github/workflows/.build-push-docker-image.yml
    with:
      image_name: ${{ github.repository }}-worker
      dockerfile: ./packaging/docker/worker.Dockerfile
      cache_mode: off # cache is really slow for this file
