name: lint

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: HatsuneMiku3939/direnv-action@v1

      - name: install backend dependencies
        run: pdm install -p backend/

      - name: install frontend dependencies
        run: pnpm --prefix frontend/ i

      - name: cache pre-commit env
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ matrix.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
