name: lint

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Wait for nix daemon to start
        if: runner.os == 'macOS'
        run: wait4path /nix/var/nix/profiles/per-user

      - name: Initialize nix environment
        run: nix develop .

      - name: install dependencies
        run: nix develop --command ./packaging/install_dependencies.sh

      - name: run pre-commit
        run: nix develop --command pre-commit run --show-diff-on-failure --color=always --all-files
