name: lint

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v30

      - name: Wait for nix daemon to start
        if: runner.os == 'macOS'
        run: wait4path /nix/var/nix/profiles/per-user

      - name: Initialize nix environment
        run: nix develop .

      - name: Setup backend pypackages cache
        uses: actions/cache@v3
        with:
          path: |
            backend/.venv/
          key: ${{ runner.os }}-${{ runner.arch }}-pypackages-${{ hashFiles('backend/uv.lock', 'proto/transcribee_proto/*.py') }}

      - name: Setup worker pypackages cache
        uses: actions/cache@v3
        with:
          path: |
            worker/.venv/
          key: ${{ runner.os }}-${{ runner.arch }}-pypackages-${{ hashFiles('worker/uv.lock', 'proto/transcribee_proto/*.py') }}

      - name: install dependencies
        run: nix develop --command ./packaging/install_dependencies.sh

      - name: cache pre-commit env
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: run pre-commit
        run: nix develop --command pre-commit run --show-diff-on-failure --color=always --all-files
