name: lint

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8.1.0
      - uses: actions/setup-node@v6
        with:
          # keep in sync with flake.nix
          node-version: 24
      - name: install pre-commit
        run: pip install pre-commit ruff poethepoet

      - name: install ubuntu dependencies
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: install web dependencies
        run: ./packaging/install_dependencies.sh

      - name: install desktop dependencies
        run: npm --prefix desktop/ ci

      - name: run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
