name: test_build

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        target: [backend, worker]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Wait for nix daemon to start
        if: runner.os == 'macOS'
        run: wait4path /nix/var/nix/profiles/per-user

      - name: Build the target
        run: nix build .#${{ matrix.target }}
